### ISSUE TITLE
Improper use of self

### ISSUE THREAD

**Issue by tisnik** [walker76/stackoversight#51]
https://github.com/walker76/stackoversight/blob/7aa0ae0a942c7a0fc30cdde1bd6f1426ba4399df/stackoversight/scraping/site.py#L23

Should be (I believe):

```
if not Site.balancer:
    Site.balancer = SiteBalancer(sessions, timeout_sec, limit)
```

because `balancer` is a class attribute

**Comment by ashersnavely** [comment]
Very good catch, didn't notice that. In fact I think I may have done that elsewhere so I'll go double check.

This one can be closed because the setup has changed.
I want to be able to scrape each site once at a time but someone should still be able to scrape multiple different sites at the same time.
So I changed it to allow multiple instances of an AbstractSite (formerly Site) object and its SiteBalancer, one for each concrete class.
